from typing import Protocol
from uuid import UUID

from beanly.modules.integrations.application.dto import FiscalReceiptResult
from beanly.modules.organizations.domain.entities import TenantContext


class FiscalLiveRepositoryPort(Protocol):
    async def get_receipt(self, context: TenantContext, receipt_id: UUID): ...
    async def list_receipts(self, context: TenantContext, **filters: object): ...
    async def operations(self, context: TenantContext, location_id: UUID): ...
    async def retry_receipt(self, context: TenantContext, receipt_id: UUID): ...
    async def finish_reconciliation(
        self, context: TenantContext, receipt_id: UUID, result: FiscalReceiptResult
    ): ...
    async def enforcement(self, context: TenantContext, location_id: UUID): ...
    async def set_enforcement(self, context: TenantContext, location_id: UUID, mode: str): ...
    async def list_routes(self, context: TenantContext, location_id: UUID | None): ...
    async def create_route(self, context: TenantContext, **values: object): ...
    async def set_route_active(self, context: TenantContext, route_id: UUID, active: bool): ...
    async def go_live_readiness(
        self,
        context: TenantContext,
        location_id: UUID,
        *,
        live_transport_enabled: bool,
        real_provider_codes: frozenset[str],
        nkt_configured: bool,
    ) -> dict[str, object]: ...


class FiscalReconciliationPort(Protocol):
    async def reconcile(self, receipt: object) -> FiscalReceiptResult | None: ...


class UnavailableFiscalReconciler:
    async def reconcile(self, receipt: object) -> FiscalReceiptResult | None:
        return None
