from datetime import datetime
from decimal import Decimal
from typing import Protocol
from uuid import UUID

from beanly.modules.sales.domain.entities import (
    OrderItem,
    PosRegister,
    RegisterShift,
    SalesOrder,
)
from beanly.modules.sales.domain.enums import OrderStatus, SaleCostStatus


class SalesRepository(Protocol):
    async def add_register(self, value: PosRegister) -> PosRegister: ...
    async def get_register(
        self, organization_id: UUID, register_id: UUID
    ) -> PosRegister | None: ...
    async def list_registers(
        self, organization_id: UUID, location_id: UUID | None
    ) -> list[PosRegister]: ...
    async def update_register(self, value: PosRegister) -> PosRegister: ...
    async def add_shift(self, value: RegisterShift) -> RegisterShift: ...
    async def get_shift(
        self, organization_id: UUID, shift_id: UUID, *, lock: bool = False
    ) -> RegisterShift | None: ...
    async def get_current_shift(
        self, organization_id: UUID, register_id: UUID
    ) -> RegisterShift | None: ...
    async def update_shift(self, value: RegisterShift) -> RegisterShift: ...
    async def count_open_orders(self, organization_id: UUID, shift_id: UUID) -> int: ...
    async def next_order_number(self) -> int: ...
    async def add_order(self, value: SalesOrder) -> SalesOrder: ...
    async def get_order(
        self, organization_id: UUID, order_id: UUID, *, lock: bool = False
    ) -> SalesOrder | None: ...
    async def get_order_by_client_id(
        self, organization_id: UUID, client_order_id: UUID
    ) -> SalesOrder | None: ...
    async def list_orders(
        self,
        organization_id: UUID,
        location_ids: tuple[UUID, ...],
        shift_id: UUID | None,
        status: OrderStatus | None,
        created_by_user_id: UUID | None,
    ) -> list[SalesOrder]: ...
    async def update_order(self, value: SalesOrder) -> SalesOrder: ...
    async def mark_order_paid(
        self,
        order_id: UUID,
        paid_by_user_id: UUID,
        paid_at: datetime,
        inventory_transaction_id: UUID | None,
        cogs_amount: Decimal,
        cogs_status: SaleCostStatus,
    ) -> None: ...
    async def get_item_by_client_id(
        self, order_id: UUID, client_item_id: UUID
    ) -> OrderItem | None: ...
    async def add_item(self, value: OrderItem) -> OrderItem: ...
    async def update_item(self, value: OrderItem) -> OrderItem: ...
    async def replace_item_configuration(self, value: OrderItem) -> OrderItem: ...
    async def delete_item(self, order_id: UUID, item_id: UUID) -> None: ...
    async def recalculate_order_totals(
        self, organization_id: UUID, order_id: UUID
    ) -> SalesOrder: ...
    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...
