from typing import Protocol
from uuid import UUID

from beanly.modules.refunds.domain.entities import Refund


class RefundRepository(Protocol):
    async def get(self, organization_id: UUID, refund_id: UUID) -> Refund | None: ...
    async def get_by_client_id(
        self, organization_id: UUID, client_refund_id: UUID
    ) -> Refund | None: ...
    async def add(self, value: Refund) -> Refund: ...
    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...
