from enum import StrEnum


class FinanceEntryType(StrEnum):
    REVENUE = "REVENUE"
    COGS = "COGS"
    INVENTORY_LOSS = "INVENTORY_LOSS"
    INVENTORY_GAIN = "INVENTORY_GAIN"
    OPERATING_EXPENSE = "OPERATING_EXPENSE"
    OTHER_INCOME = "OTHER_INCOME"
    OTHER_EXPENSE = "OTHER_EXPENSE"


class ExpenseStatus(StrEnum):
    DRAFT = "DRAFT"
    POSTED = "POSTED"
    REVERSED = "REVERSED"


class CashAccountType(StrEnum):
    CASH = "CASH"
    CARD_CLEARING = "CARD_CLEARING"
    BANK = "BANK"
    OTHER = "OTHER"


class CashMovementType(StrEnum):
    SUPPLIER_PAYMENT = "SUPPLIER_PAYMENT"
    OWNER_CONTRIBUTION = "OWNER_CONTRIBUTION"
    OWNER_WITHDRAWAL = "OWNER_WITHDRAWAL"
    OTHER_INFLOW = "OTHER_INFLOW"
    OTHER_OUTFLOW = "OTHER_OUTFLOW"
    TRANSFER = "TRANSFER"


class CashFlowActivity(StrEnum):
    OPERATING = "OPERATING"
    INVESTING = "INVESTING"
    FINANCING = "FINANCING"
