from datetime import datetime
from decimal import Decimal
from typing import Protocol
from uuid import UUID

from beanly.modules.finance.domain.entities import (
    CashAccount,
    CashEntry,
    CashMovement,
    Expense,
    ExpenseCategory,
    FinanceEntry,
)
from beanly.modules.finance.domain.enums import FinanceEntryType


class FinanceRepository(Protocol):
    async def currency(self, organization_id: UUID) -> str: ...
    async def location_exists(self, organization_id: UUID, location_id: UUID) -> bool: ...
    async def add_finance_entry(self, value: FinanceEntry) -> bool: ...
    async def add_cash_entry(self, value: CashEntry) -> bool: ...
    async def find_finance_entry(
        self, organization_id: UUID, source_type: str, source_id: UUID, entry_role: str
    ) -> FinanceEntry | None: ...
    async def find_cash_entry(
        self, organization_id: UUID, source_type: str, source_id: UUID, entry_role: str
    ) -> CashEntry | None: ...
    async def system_account(
        self,
        organization_id: UUID,
        location_id: UUID,
        method: str,
        currency_code: str,
    ) -> CashAccount: ...
    async def add_category(self, value: ExpenseCategory) -> None: ...
    async def list_categories(self, organization_id: UUID) -> list[ExpenseCategory]: ...
    async def get_category(
        self, organization_id: UUID, category_id: UUID, *, lock: bool = False
    ) -> ExpenseCategory | None: ...
    async def update_category(self, value: ExpenseCategory) -> None: ...
    async def add_account(self, value: CashAccount) -> None: ...
    async def list_accounts(self, organization_id: UUID) -> list[CashAccount]: ...
    async def get_account(
        self, organization_id: UUID, account_id: UUID, *, lock: bool = False
    ) -> CashAccount | None: ...
    async def update_account(self, value: CashAccount) -> None: ...
    async def add_expense(self, value: Expense) -> None: ...
    async def list_expenses(self, organization_id: UUID) -> list[Expense]: ...
    async def get_expense(
        self, organization_id: UUID, expense_id: UUID, *, lock: bool = False
    ) -> Expense | None: ...
    async def update_expense(self, value: Expense) -> None: ...
    async def add_cash_movement(self, value: CashMovement) -> None: ...
    async def list_cash_movements(self, organization_id: UUID) -> list[CashMovement]: ...
    async def get_cash_movement(
        self, organization_id: UUID, movement_id: UUID, *, lock: bool = False
    ) -> CashMovement | None: ...
    async def update_cash_movement(self, value: CashMovement) -> None: ...
    async def list_finance_entries(
        self,
        organization_id: UUID,
        date_from: datetime | None,
        date_to: datetime | None,
        location_id: UUID | None,
        entry_type: FinanceEntryType | None,
        source_type: str | None,
        source_id: UUID | None,
    ) -> list[FinanceEntry]: ...
    async def finance_totals(
        self,
        organization_id: UUID,
        date_from: datetime,
        date_to: datetime,
        location_id: UUID | None,
    ) -> dict[str, Decimal]: ...
    async def incomplete_cogs_count(
        self,
        organization_id: UUID,
        date_from: datetime,
        date_to: datetime,
        location_id: UUID | None,
    ) -> int: ...
    async def expense_breakdown(
        self,
        organization_id: UUID,
        date_from: datetime,
        date_to: datetime,
        location_id: UUID | None,
    ) -> list[tuple[UUID | None, str, Decimal]]: ...
    async def location_totals(
        self, organization_id: UUID, date_from: datetime, date_to: datetime
    ) -> list[tuple[UUID | None, str, dict[str, Decimal]]]: ...
    async def cash_totals(
        self,
        organization_id: UUID,
        date_from: datetime,
        date_to: datetime,
        location_id: UUID | None,
    ) -> tuple[int, dict[str, tuple[int, int]]]: ...
    async def data_as_of(
        self, organization_id: UUID, location_id: UUID | None
    ) -> datetime | None: ...
    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...
