from typing import Protocol
from uuid import UUID

from beanly.modules.menu.domain.entities import (
    Category,
    Product,
    ProductLocationSetting,
    ProductVariant,
    Recipe,
    VariantPrice,
)
from beanly.modules.menu.domain.enums import ProductStatus


class MenuRepository(Protocol):
    async def add_category(self, value: Category) -> Category: ...
    async def get_category(self, organization_id: UUID, category_id: UUID) -> Category | None: ...
    async def lock_category(self, organization_id: UUID, category_id: UUID) -> bool: ...
    async def list_categories(self, organization_id: UUID) -> list[Category]: ...
    async def update_category(self, value: Category) -> Category: ...
    async def add_product(self, value: Product) -> Product: ...
    async def get_product(self, organization_id: UUID, product_id: UUID) -> Product | None: ...
    async def lock_product(
        self, organization_id: UUID, product_id: UUID
    ) -> ProductStatus | None: ...
    async def list_products(
        self,
        organization_id: UUID,
        category_id: UUID | None,
        status: ProductStatus | None,
        search: str | None,
        location_id: UUID | None,
    ) -> list[Product]: ...
    async def update_product(self, value: Product) -> Product: ...
    async def add_variant(self, value: ProductVariant) -> ProductVariant: ...
    async def get_variant(
        self, organization_id: UUID, variant_id: UUID
    ) -> ProductVariant | None: ...
    async def update_variant(self, value: ProductVariant) -> ProductVariant: ...
    async def clear_default_variant(self, organization_id: UUID, product_id: UUID) -> None: ...
    async def first_active_variant(
        self, organization_id: UUID, product_id: UUID, exclude_id: UUID
    ) -> ProductVariant | None: ...
    async def get_recipe(self, organization_id: UUID, variant_id: UUID) -> Recipe | None: ...
    async def list_recipes(
        self, organization_id: UUID, variant_ids: tuple[UUID, ...]
    ) -> dict[UUID, Recipe]: ...
    async def replace_recipe(self, value: Recipe) -> tuple[Recipe, bool]: ...
    async def set_variant_price(self, value: VariantPrice) -> VariantPrice: ...
    async def delete_variant_price(
        self, organization_id: UUID, variant_id: UUID, location_id: UUID
    ) -> None: ...
    async def get_effective_price(
        self, organization_id: UUID, variant_id: UUID, location_id: UUID | None
    ) -> int | None: ...
    async def get_effective_prices(
        self, organization_id: UUID, variant_ids: tuple[UUID, ...], location_id: UUID
    ) -> dict[UUID, int]: ...
    async def get_location_prices(
        self, organization_id: UUID, variant_ids: tuple[UUID, ...], location_id: UUID
    ) -> dict[UUID, int]: ...
    async def set_product_location(
        self, value: ProductLocationSetting
    ) -> ProductLocationSetting: ...
    async def get_product_location(
        self, organization_id: UUID, product_id: UUID, location_id: UUID
    ) -> ProductLocationSetting | None: ...
    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...
