from enum import StrEnum


class OnboardingStatus(StrEnum):
    NOT_STARTED = "NOT_STARTED"
    IN_PROGRESS = "IN_PROGRESS"
    READY_FOR_POS = "READY_FOR_POS"
    COMPLETED = "COMPLETED"


class ImportStatus(StrEnum):
    UPLOADED = "UPLOADED"
    PARSING = "PARSING"
    NEEDS_REVIEW = "NEEDS_REVIEW"
    READY = "READY"
    APPLYING = "APPLYING"
    APPLIED = "APPLIED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class ImportEntityType(StrEnum):
    CATEGORY = "CATEGORY"
    INVENTORY_ITEM = "INVENTORY_ITEM"
    PRODUCT = "PRODUCT"
    VARIANT = "VARIANT"
    RECIPE = "RECIPE"
    MODIFIER_GROUP = "MODIFIER_GROUP"
    MODIFIER_OPTION = "MODIFIER_OPTION"
    LOCATION_PRICE = "LOCATION_PRICE"
    OPENING_BALANCE = "OPENING_BALANCE"


class ImportResolution(StrEnum):
    CREATE = "CREATE"
    MATCH_EXISTING = "MATCH_EXISTING"
    SKIP = "SKIP"


class ImportSourceType(StrEnum):
    BEANLY_TEMPLATE = "BEANLY_TEMPLATE"
    BEANLY_SPREADSHEET = "BEANLY_SPREADSHEET"
    GENERIC_SPREADSHEET = "GENERIC_SPREADSHEET"
    POSTER_EXPORT = "POSTER_EXPORT"
    AI_EXTRACTION = "AI_EXTRACTION"


class UploadSourceType(StrEnum):
    AUTO = "AUTO"
    BEANLY_SPREADSHEET = "BEANLY_SPREADSHEET"
    GENERIC_SPREADSHEET = "GENERIC_SPREADSHEET"
    POSTER = "POSTER"
