from typing import Protocol
from uuid import UUID

from beanly.modules.employees.domain.entities import Employee
from beanly.modules.organizations.domain.entities import TeamMember
from beanly.modules.organizations.domain.enums import MembershipRole


class EmployeeRepository(Protocol):
    async def add(self, employee: Employee) -> Employee: ...

    async def replace_locations(
        self, employee_id: UUID, location_ids: tuple[UUID, ...]
    ) -> None: ...

    async def list_for_organization(self, organization_id: UUID) -> list[Employee]: ...

    async def get(self, organization_id: UUID, employee_id: UUID) -> Employee | None: ...

    async def update(self, employee: Employee) -> Employee: ...

    async def get_by_user(self, organization_id: UUID, user_id: UUID) -> Employee | None: ...

    async def list_team_members(self, organization_id: UUID) -> list[TeamMember]: ...

    async def locations_belong_to_organization(
        self, organization_id: UUID, location_ids: tuple[UUID, ...]
    ) -> bool: ...

    async def membership_role(
        self, organization_id: UUID, user_id: UUID
    ) -> MembershipRole | None: ...

    async def suspend_membership(self, organization_id: UUID, user_id: UUID) -> None: ...

    async def commit(self) -> None: ...

    async def rollback(self) -> None: ...
